version: "3.7"

services:
  coworker:
    build: ./
    command: npm start
    environment:
      POSTGRES_URI: postgres://postgres:postgres123@postgres:5432/coworker
    ports:
      - "5000:5000"

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: coworker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
