version: "3.7"

services:
  coworker:
    build: ./
    command: npm start
    environment:
      POSTGRES_URI: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DB}
    ports:
      - "5000:5000"

  postgres:
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_HOST: ${PG_HOST}
    build: ./postgres
    ports:
      - "5432:5432"
